AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GraphQL Messages API using NodeJS and Typescript

Parameters:
  APIName:
    Type: String
    Description: The name of the GraphQL API
    MinLength: 3
    MaxLength: 20
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
    Default: MessagesGraphQLAPI

Resources:

  DynamoDBMessagesTable:
    Description: "Data store for AWS AppSync Messages"
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${APIName}-messages-table
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  DynamoDBDevicesTable:
    Description: "Data store for AWS AppSync Devices"
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${APIName}-devices-table
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AppSyncApi:
    Type: "AWS::AppSync::GraphQLApi"
    Description: "The GraphQL API for the Messages"
    Properties:
      AuthenticationType: "API_KEY"
      Name: !Sub ${APIName}

  AppSyncSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      DefinitionS3Location: ./schema.graphql

  AppSyncLambdaServiceRole:
    Type: AWS::IAM::Role
    Description: "An IAM Role to allow AWS AppSync to invoke lambda functions"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncInvokeLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt MessagesLambdaFunction.Arn

  MessagesLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: ./handler.zip
      Handler: appsync.handler
      Timeout: 10
      Environment:
        Variables:
          MESSAGES_DYNAMODB_TABLE: !Ref DynamoDBMessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBMessagesTable

  MessagesLambdaDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: !Sub ${APIName}_MessagesLambdaDataSource
      Description: "The AppSync Lambda Data Source"
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt MessagesLambdaFunction.Arn

  # AppSync API Resolvers:

  GetMessageQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getMessage
      DataSourceName: !GetAtt MessagesLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Invoke",
          "payload": {
            "field": "storeMessage",
            "arguments": $utils.toJson($context.arguments)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AllMessagesQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: allMessages
      DataSourceName: !GetAtt MessagesLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Invoke",
          "payload": {
            "field": "allMessages",
            "arguments": $utils.toJson($context.arguments)
          }
        }
      ResponseMappingTemplate: "$utils.toJson($context.result.items)"

  StoreMessageMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: storeMessage
      DataSourceName: !GetAtt MessagesLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Invoke",
          "payload": {
            "field": "storeMessage",
            "arguments": $utils.toJson($context.arguments)
          }
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result)
#
#  GetDeviceQueryResolver:
#    Type: "AWS::AppSync::Resolver"
#    DependsOn: AppSyncSchema
#    Properties:
#      ApiId: !GetAtt AppSyncApi.ApiId
#      TypeName: Query
#      FieldName: getDevice
#      DataSourceName: !GetAtt AppSyncDevicesTableDataSource.Name
#      RequestMappingTemplate: |
#        {
#          "version": "2017-02-28",
#          "operation": "GetItem",
#          "key": {
#            "deviceId": $util.dynamodb.toDynamoDBJson($ctx.args.deviceId)
#          }
#        }
#      ResponseMappingTemplate: "$util.toJson($ctx.result)"

Outputs:

  DynamoDBMessagesTableName:
    Description: The name of the DynamoDB Table
    Value: !Ref DynamoDBMessagesTable

  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value: !GetAtt AppSyncApi.GraphQLUrl

  GraphQLApiId:
    Description: The API ID of the GraphQL API
    Value: !GetAtt AppSyncApi.ApiId