AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM app using NodeJS and Typescript

Globals:
  Function:
    Timeout: 3

Resources:
  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: message-lambda/dist/
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        Message:
          Type: Api
          Properties:
            Path: /message
            Method: get