AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM app using NodeJS and Typescript

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: message/
      Handler: dist/index.lambdaHandler
      Runtime: nodejs6.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /message
            Method: get